# appveyor.yml

environment:
  matrix:
    - SCALA_VERSION: 2.12.8

platform:
  - x86

install:
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%

test_script:
  - sbt ++%SCALA_VERSION% "run https://repo1.maven.org"

cache:
  - C:\sbt\
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2

build: off
